---
- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tags:
    - step001
    - pre_infrastructure
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure"

- name: Check if user and subscription exists in Active Directory
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  environment:
    AZURE_CLIENT_ID: "{{azure_service_principal}}"
    AZURE_TENANT: "{{azure_tenant}}"
    AZURE_SECRET: "{{azure_password}}"
    AZURE_SUBSCRIPTION_ID: "{{azure_subscription_id}}"
    AZURE_CONFIG_DIR: "{{ output_dir }}/.azure-{{project_tag}}"
    PATH: '{{ output_dir }}:/bin:/usr/bin:/usr/local/bin'
  tasks:
    - name: Check if email is *@redhat.com
      fail:
        msg: User is not a Red Hat associate
      when: '"@redhat.com" not in email'
    - name: Initialize azureProfile.json
      command: /usr/bin/az login --service-principal -u {{ azure_service_principal }} -p {{ azure_password }} --tenant {{ azure_tenant }}
    - name: Checking if user is in Active Directory
      register: azuser
      azure.azcollection.azure_rm_aduser_info:
        auth_source: cli
        user_principal_name: "{{ email }}"
        tenant: "{{ azure_tenant }}"
    - name: show dictionary
      debug:
        msg: "{{item.key}}: {{item.value}}"
      with_dict: azuser
