---
# Implement your Pre Workload deployment tasks here
# -------------------------------------------------


# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Copy a hashicorp vault values file to bastion
  ansible.builtin.copy:
    src: files/hashicorp_vault_helm_overrides.yml
    dest: /tmp/hashicorp_vault_helm_overrides.yml

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Software checks completed successfully"
  when:
  - not silent|bool
  - workload_shared_deployment|default(False)
