---
become_override: false
ocp_username: wkulhane-redhat.com
silent: false

ocp4_workload_aquasec_namespace: aquasec
ocp4_workload_aquasec_sockshop_project: sock-shop
ocp4_workload_aquasec_db_secret_name: aqua-database-password