---
# Implement your Pre Workload deployment tasks here
# -------------------------------------------------

- name: Create aquasec-lab directory
  ansible.builtin.file:
    path: "~/{{ ocp4_workload_aquasec_labdir }}"
    state: directory
    mode: '0755'

- name: Copy Enforcer file to bastion
  ansible.builtin.template:
    src: aquasec-EnforcerGroup.j2
    dest: "~/{{ ocp4_workload_aquasec_labdir }}/EnforcerGroup.json"

- name: Copy Kube Enforcer file to bastion
  ansible.builtin.template:
    src: aquasec-KubeEnforcerGroup.j2
    dest: "~/{{ ocp4_workload_aquasec_labdir }}/KubeEnforcerGroup.json"

# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when:
  - not silent|bool
  - not workload_shared_deployment|default(False)

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Software checks completed successfully"
  when:
  - not silent|bool
  - workload_shared_deployment|default(False)
