---
- name: Create {{ ocp4_workload_aquasec_namespace }} namespace
  kubernetes.core.k8s:
    name: "{{ ocp4_workload_aquasec_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create secret for {{ ocp4_workload_aquasec_namespace }}
  kubernetes.core.k8s:
    state: present
    template: aquasec-db-secret.j2




- name: Create Sock Shop project
  kubernetes.core.k8s:
    state: present
    template: sockshop_project.j2

# Deploy Sock Shop
- name: Deploy Sock Shop
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_prisma_sockshop_project }}"
    template: sockshop.j2

# Expose Sock Shop to the world
- name: Deploy Sock Shop Cloud route
  kubernetes.core.k8s:
    state: present
    template: sockshop_route.j2

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
