---
become_override: false
ocp_username: wkulhane-redhat.com
silent: false
remove_k8s_venv: false

private_registry_url: "private-registry.nginx.com/nginx-ic-nap"
image_name: "nginx-plus-ingress:2.1.1-ubi"

nginx_namespace: nginx-ingresss
nginx_imagestream: f5-nginx



# If your workload needs customization options provide variables to be used.
# Variable names must be prefixed by the role name "<role name>_<variable>".
# So because this example workload is called "ocp4_workload_example" the variables
# should be named "ocp4_workload_example_dedicated_cluster_variable".
#
# You can override the defaults as parameters to the Ansible run that runs
# your workload.

ocp4_workload_example_dedicated_cluster_variable_1: "value 1"
ocp4_workload_example_dedicated_cluster_variable_2: "value 2"
ocp4_workload_example_dedicated_cluster_user_info: "This is the OCP4 Example Workload"
ocp4_workload_example_dedicated_cluster_namespace: "ocp4-workload-example-{{ ocp_username }}"
