---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: create {{ ocp4_workload_nginxplus_namespace }} namespace/project
  kubernetes.core.k8s:
    name: "{{ ocp4_workload_nginxplus_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create secret for {{ ocp4_workload_nginxplus_base_url }}
  kubernetes.core.k8s:
    state: present
    template: nginx-registry-secret.j2

- name: Create imagestream
  kubernetes.core.k8s:
    state: present
    template: nginx-imagestream.j2

- name: get imageregistry url
  kubernetes.core.k8s_info:
    kind: ImageStream
    name: "{{ ocp4_workload_nginxplus_imagestream }}"
    namespace: "{{ ocp4_workload_nginxplus_namespace }}"
  register: ocp4_workload_nginxplus_imagestream_url

- name: set imageregistry url
  set_fact:
    # yamllint disable-line rule:line-length
    ocp4_workload_nginxplus_registry_url: "{{ ocp4_workload_nginxplus_imagestream_url.resources[0].status.dockerImageRepository }}"

- name: Create operatorgroup
  kubernetes.core.k8s:
    state: present
    template: nginx-operatorgroup.j2

- name: Create subscription
  kubernetes.core.k8s:
    state: present
    template: nginx-subscription.j2

- name: Pause for 30 seconds while operator installs
  pause:
    seconds: 30

- name: Create cluster role
  kubernetes.core.k8s:
    state: present
    template: nginx-cluster-role.j2

- name: Create cluster role binding
  kubernetes.core.k8s:
    state: present
    template: nginx-cluster-role-binding.j2

- name: Create secret default-server-secret
  kubernetes.core.k8s:
    state: present
    template: nginx-tls-secret.j2

- name: Create SecurityContextConstraints
  kubernetes.core.k8s:
    state: present
    template: nginx-scc.j2

- name: Create controller
  kubernetes.core.k8s:
    state: present
    template: nginx-controller.j2
  when: ocp4_workload_nginxplus_install_controller == true

- name: Pause for 30 seconds before removing {{ ocp4_workload_nginxplus_secret_name }} secret
  pause:
    seconds: 30

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool