---
- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

# To Do: Implement your workload deployment tasks here
# -------------------------------------------------------------------------

- name: create {{ ocp4_workload_nginxplus_namespace }} namespace/project
  kubernetes.core.k8s:
    name: "{{ ocp4_workload_nginxplus_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: create secret for quay.io
  # yamllint disable-line rule:line-length
  shell: oc create secret docker-registry quay-login --docker-username="{{ ocp4_workload_nginxplus_quay_username }}" --docker-server="{{ ocp4_workload_nginxplus_private_registry_url }}" --docker-password="{{ ocp4_workload_nginxplus_quay_password }}" -n "{{ ocp4_workload_nginxplus_namespace }}"  || /bin/true


- name: import image to imagestream
  # yamllint disable-line rule:line-length
  shell: oc import-image "{{ ocp4_workload_nginxplus_private_registry_url}}"/"{{ ocp4_workload_nginxplus_image_name }}:{{ ocp4_workload_nginxplus_image_tag }}" -n "{{ ocp4_workload_nginxplus_namespace }}" --confirm  || /bin/true

- name: get imageregistry url
  kubernetes.core.k8s_info:
    kind: ImageStream
    name: "{{ ocp4_workload_nginxplus_imagestream }}"
    namespace: "{{ ocp4_workload_nginxplus_namespace }}"
  register: ocp4_workload_nginxplus_imagestream_url

- name: set imageregistry url
  set_fact:
    ocp4_workload_nginxplus_registry_url: "{{ ocp4_workload_nginxplus_imagestream_url.resources[0].status.dockerImageRepository }}"

- name: Create objects for NGINX IC- operatorgroup
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-operatorgroup.j2

- name: Create objects for NGINX IC- subscription
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-subscription.j2

- name: Pause for 30 seconds while operator installs
  pause:
    seconds: 30

- name: Create objects for NGINX IC- cluster role
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-clusterrole.j2

- name: Create objects for NGINX IC- cluster role binding
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-clusterrolebinding.j2

- name: Create objects for NGINX IC- secret
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-secret.j2

- name: Create objects for NGINX IC- scc
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-scc.j2

- name: Create objects for NGINX IC- controller
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
    - nginx-controller.j2
  when: ocp4_workload_nginxplus_install_controller == true

- name: Pause for 30 seconds while ingress controller installs before removing quay secret
  pause:
    seconds: 30

# Leave this as the last task in the playbook.
# --------------------------------------------
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool